"""Fix nullable user fields

Revision ID: 2ab33a4a22a3
Revises: e0088cbd93cc
Create Date: 2026-05-22 11:00:59.447810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2ab33a4a22a3"
down_revision: Union[str, Sequence[str], None] = "e0088cbd93cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("phone", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("phone", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
