"""Fix first_name typo in profiles

Revision ID: 09b93d759471
Revises: 2ab33a4a22a3
Create Date: 2026-05-22 11:55:34.338773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "09b93d759471"
down_revision: Union[str, Sequence[str], None] = "2ab33a4a22a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_name", sa.String(length=32), nullable=True))
        batch_op.drop_column("firs_name")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("firs_name", sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_column("first_name")

    # ### end Alembic commands ###
