"""Fix order_product_association unique constraints

Revision ID: 139bbe5398da
Revises: c521fbb049b8
Create Date: 2026-05-23 12:45:00.396515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "139bbe5398da"
down_revision: Union[str, Sequence[str], None] = "c521fbb049b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_product_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", "product_id", name="idx_unique_order_product"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("promocode", sa.String(), nullable=True))
        batch_op.drop_column("promocod")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("promocod", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("promocode")

    op.drop_table("order_product_association")
    # ### end Alembic commands ###
