"""Add count column to associtate table

Revision ID: 613aa5d75701
Revises: 0479a5e2f7b9
Create Date: 2026-05-23 16:04:20.823013

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "613aa5d75701"
down_revision: Union[str, Sequence[str], None] = "0479a5e2f7b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_product_association", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("count", sa.Integer(), server_default="1", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_product_association", schema=None) as batch_op:
        batch_op.drop_column("count")

    # ### end Alembic commands ###
