"""add unit_price

Revision ID: ccb8a8c51d82
Revises: 776697b79616
Create Date: 2026-05-23 22:00:18.148197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ccb8a8c51d82"
down_revision: Union[str, Sequence[str], None] = "776697b79616"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_product_association", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("unit_price", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_product_association", schema=None) as batch_op:
        batch_op.drop_column("unit_price")

    # ### end Alembic commands ###
